---
title: "R Notebook"
---
# 使用說明
* 將從 crowdtangle 下載下來的檔案分別拆成不同候選人的檔案
* 更新時會確認歷史資料，只更新新的

```{r}
library(readr)
library(plyr)
library(dplyr)
library(tidyr)
library(lubridate)
library(data.table)
```
# 之後更新
```{r}
file<-read_csv("temp1012.csv",col_types = cols(.default = "c")) #檔名

colnames(file)[2]<-"UserName"
file$`Post Created`<-as.character(ymd_hms(file$`Post Created`))
hoho_fb<-read_csv("~/readr/2024_president_socialmedia/hoho_fb.csv",col_types = cols(.default = "c"))
kp_fb<-read_csv("~/readr/2024_president_socialmedia/kp_fb.csv",col_types = cols(.default = "c"))
lai_fb<-read_csv("~/readr/2024_president_socialmedia/lai_fb.csv",col_types = cols(.default = "c"))
kuo_fb<-read_csv("~/readr/2024_president_socialmedia/kuo_fb.csv",col_types = cols(.default = "c"))

ID_list<-unique(file$UserName)

for(q in 1:length(ID_list)){
  print(q)
  temp<-filter(file,UserName==ID_list[q])
  if(nrow(temp)==0)
    next
  
  if(ID_list[q]=="houyuih"){
    name="hoho"
    time<-hoho_fb$`Post Created`[nrow(hoho_fb)]
    temp<-filter(temp,`Post Created`>time)
    if(nrow(temp)==0)
      next
    colnames(temp)<-colnames(hoho_fb)
    temp<-rbind(hoho_fb,temp)
    temp<-unique(temp)
    temp<-temp[order(temp$`Post Created`,decreasing = F),]
    
    }else if(ID_list[q]=="TerryGou1018"){
      name="kuo"
      time<-kuo_fb$`Post Created`[nrow(kuo_fb)]
      temp<-filter(temp,`Post Created`>time)
      if(nrow(temp)==0)
        next
      colnames(temp)<-colnames(kuo_fb)
      temp<-rbind(kuo_fb,temp)
      temp<-unique(temp)
      temp<-temp[order(temp$`Post Created`,decreasing = F),]

    }else if(ID_list[q]=="chingte"){
      name="lai"
      time<-lai_fb$`Post Created`[nrow(lai_fb)]
      temp<-filter(temp,`Post Created`>time)
      if(nrow(temp)==0)
        next
      colnames(temp)<-colnames(lai_fb)
      temp<-rbind(lai_fb,temp)
      temp<-unique(temp)
      temp<-temp[order(temp$`Post Created`,decreasing = F),]
      
    }else{
      name="kp"
      time<-kp_fb$`Post Created`[nrow(kp_fb)]
      temp<-filter(temp,`Post Created`>time)
      if(nrow(temp)==0)
        next
      colnames(temp)<-colnames(kp_fb)
      temp<-rbind(kp_fb,temp)
      temp<-unique(temp)
      temp<-temp[order(temp$`Post Created`,decreasing = F),]
    }
  temp[]<- lapply(temp, as.character)
  write.csv(temp,paste0("~/readr/2024_president_socialmedia/",name,"_fbtest.csv"),row.names=FALSE)
}

```


# 首次創建
```{r}
file<-read_csv("fb2018-2023.csv",col_types = cols(.default = "c")) #檔名
```

```{r}
colnames(file)[2]<-"UserName"
ID_list<-unique(file$UserName)

for(q in 1:length(ID_list)){

    print(q)
  temp<-filter(file,UserName==ID_list[q])
  temp$`Facebook Id` <- format(temp$`Facebook Id`, scientific = FALSE)
  temp$`Post Created`<-ymd_hms(temp$`Post Created`)
  temp$`Post Created Time`<-as.character(substr(temp$`Post Created`,12,19))
  if(ID_list[q]=="houyuih"){name="hoho"}
  if(ID_list[q]=="TerryGou1018"){name="kuo"}
  if(ID_list[q]=="chingte"){name="lai"}
  if(ID_list[q]=="DoctorKoWJ"){name="kp"}
  temp[]<- lapply(temp, as.character)
  write.csv(temp,paste0("~/readr/2024_president_socialmedia/",name,"_fb.csv"),row.names=FALSE)
}
```


# 補之前的資料 kp
```{r}
temp<-read_csv("~/readr/2024_president_socialmedia/kp_fb.csv",col_types = cols(.default = "c"))
old<-read_csv("/Users/mac/Downloads/kp_fb.csv",col_types = cols(.default = "c"))

colnames(old)[2]<-"UserName"
colnames(temp)[2]<-"UserName"
old<-filter(old,UserName=="DoctorKoWJ")
old$`Total Interactions (weighted  —  Likes 1x Shares 1x Comments 1x Love 1x Wow 1x Haha 1x Sad 1x Angry 1x Care 1x )`<-NULL

old$`Post Created`<-as.character(ymd_hms(old$`Post Created`,tz="UTC"))
old$`Page Created`<-as.character(ymd_hms(old$`Page Created`,tz="UTC"))
old$`Post Created Time`<-as.character(substr(old$`Post Created`,12,19))
old$`Video Share Status`<-ifelse(old$`Video Share Status`=="",NA,old$`Video Share Status`)
old$Link<-ifelse(old$Link=="",NA,old$Link)
old$`Final Link`<-ifelse(old$`Final Link`=="",NA,old$`Final Link`)
old$`Image Text`<-ifelse(old$`Image Text`=="",NA,old$`Image Text`)
old$`Link Text`<-ifelse(old$`Link Text`=="",NA,old$`Link Text`)
old$Description<-ifelse(old$Description=="",NA,old$Description)
old$`Sponsor Id`<-ifelse(old$`Sponsor Id`=="",NA,old$`Sponsor Id`)
old$`Sponsor Name`<-ifelse(old$`Sponsor Name`=="",NA,old$`Sponsor Name`)
old$`Sponsor Category`<-ifelse(old$`Sponsor Category`=="",NA,old$`Sponsor Category`)
colnames(old)<-colnames(temp)
temp<-rbind(temp,old)
temp$`Total Interactions`<-gsub(",","",temp$`Total Interactions`)
temp<-unique(temp)
temp<-temp[order(temp$`Post Created`,decreasing = F),]
temp[]<- lapply(temp, as.character)
write.csv(temp,paste0("~/readr/2024_president_socialmedia/kp_fb.csv"),row.names=FALSE)
```

# 補之前的資料 lai
```{r}
temp<-read_csv("~/readr/2024_president_socialmedia/lai_fb.csv",col_types = cols(.default = "c"))
old<-read_csv("~/readr/2023_president_discussion/discussion/william_fb.csv",col_types = cols(.default = "c"))

colnames(old)[2]<-"UserName"
colnames(temp)[2]<-"UserName"
old<-filter(old,UserName=="chingte")
old$`Total Interactions (weighted  —  Likes 1x Shares 1x Comments 1x Love 1x Wow 1x Haha 1x Sad 1x Angry 1x Care 1x )`<-NULL

old$`Post Created`<-as.character(ymd_hms(old$`Post Created`,tz="UTC"))
old$`Page Created`<-as.character(ymd_hms(old$`Page Created`,tz="UTC"))
old$`Post Created Time`<-as.character(substr(old$`Post Created`,12,19))
old$`Video Share Status`<-ifelse(old$`Video Share Status`=="",NA,old$`Video Share Status`)
old$Link<-ifelse(old$Link=="",NA,old$Link)
old$`Final Link`<-ifelse(old$`Final Link`=="",NA,old$`Final Link`)
old$`Image Text`<-ifelse(old$`Image Text`=="",NA,old$`Image Text`)
old$`Link Text`<-ifelse(old$`Link Text`=="",NA,old$`Link Text`)
old$Description<-ifelse(old$Description=="",NA,old$Description)
old$`Sponsor Id`<-ifelse(old$`Sponsor Id`=="",NA,old$`Sponsor Id`)
old$`Sponsor Name`<-ifelse(old$`Sponsor Name`=="",NA,old$`Sponsor Name`)
old$`Sponsor Category`<-ifelse(old$`Sponsor Category`=="",NA,old$`Sponsor Category`)
colnames(old)<-colnames(temp)
temp<-rbind(temp,old)
temp$`Facebook Id`<-gsub(" ","",temp$`Facebook Id`)
temp$`Total Interactions`<-gsub(",","",temp$`Total Interactions`)
temp<-unique(temp)
temp<-temp[order(temp$`Post Created`,decreasing = F),]
temp[]<- lapply(temp, as.character)
write.csv(temp,paste0("~/readr/2024_president_socialmedia/lai_fb.csv"),row.names=FALSE)
```

# 補之前的資料 ho
```{r}
temp<-read_csv("~/readr/2024_president_socialmedia/hoho_fb.csv",col_types = cols(.default = "c"))
old<-read_csv("/Users/mac/Downloads/hoho_fb.csv",col_types = cols(.default = "c"))

colnames(old)[2]<-"UserName"
colnames(temp)[2]<-"UserName"
old<-filter(old,UserName=="houyuih")
old$`Total Interactions (weighted  —  Likes 1x Shares 1x Comments 1x Love 1x Wow 1x Haha 1x Sad 1x Angry 1x Care 1x )`<-NULL

old$`Post Created`<-as.character(ymd_hms(old$`Post Created`,tz="UTC"))
old$`Page Created`<-as.character(ymd_hms(old$`Page Created`,tz="UTC"))
old$`Post Created Time`<-as.character(substr(old$`Post Created`,12,19))
old$`Video Share Status`<-ifelse(old$`Video Share Status`=="",NA,old$`Video Share Status`)
old$Link<-ifelse(old$Link=="",NA,old$Link)
old$`Final Link`<-ifelse(old$`Final Link`=="",NA,old$`Final Link`)
old$`Image Text`<-ifelse(old$`Image Text`=="",NA,old$`Image Text`)
old$`Link Text`<-ifelse(old$`Link Text`=="",NA,old$`Link Text`)
old$Description<-ifelse(old$Description=="",NA,old$Description)
old$`Sponsor Id`<-ifelse(old$`Sponsor Id`=="",NA,old$`Sponsor Id`)
old$`Sponsor Name`<-ifelse(old$`Sponsor Name`=="",NA,old$`Sponsor Name`)
old$`Sponsor Category`<-ifelse(old$`Sponsor Category`=="",NA,old$`Sponsor Category`)
colnames(old)<-colnames(temp)
temp<-rbind(temp,old)
temp$`Total Interactions`<-gsub(",","",temp$`Total Interactions`)
temp<-unique(temp)
temp<-temp[order(temp$`Post Created`,decreasing = F),]
temp[]<- lapply(temp, as.character)
write.csv(temp,paste0("~/readr/2024_president_socialmedia/hoho_fb.csv"),row.names=FALSE)
```

#kuo 處理
```{r}
temp<-read_csv("~/readr/2024_president_socialmedia/kuo_fb.csv",col_types = cols(.default = "c"))

colnames(temp)[2]<-"UserName"

temp$`Total Interactions`<-gsub(",","",temp$`Total Interactions`)
temp<-unique(temp)
temp<-temp[order(temp$`Post Created`,decreasing = F),]
temp[]<- lapply(temp, as.character)
write.csv(temp,paste0("~/readr/2024_president_socialmedia/kuo_fb.csv"),row.names=FALSE)
```

